extra-y := vmlinux.lds

obj-y += \
	cpuinfo.o \
	early_printk.o \
	globals.o \
	idle.o \
	irq.o \
	process.o \
	ptrace.o \
	sections.o \
	setup.o \
	stacktrace.o \
	time.o

obj-$(CONFIG_SMP) += smp.o
