name: Cache GC

on:
  schedule:
    - cron: "23 3 * * *"
  workflow_dispatch:

concurrency:
  group: hestia-gc
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  gc:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: read
    steps:
      - uses: NixOS/nix-installer-action@main
      - uses: Mic92/hestia@v2
      - name: Run garbage collection
        run: '"$HESTIA_BIN" gc'
        env:
          GITHUB_TOKEN: ${{ github.token }}
