on:
  - push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build . --print-build-logs
      - uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: result
